import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jorju
 */
public class Dados extends javax.swing.JFrame {

    /**
     * Creates new form Dados
     */
    private Timer timer;
    private int contador;

    public Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dadito1 = new javax.swing.JLabel();
        dadito2 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Lanzar Dados ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        dadito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dados/2.png"))); // NOI18N
        getContentPane().add(dadito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        dadito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dados/5.png"))); // NOI18N
        getContentPane().add(dadito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        Resultado.setEditable(false);
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 197, -1));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jgdd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 267, 232));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void iniciarAnimacionDados() {
    timer = new Timer();
    contador = 0;
    
    TimerTask task = new TimerTask() {
        @Override
        public void run() {
            contador++;
            
            if (contador <= 10) {  // Cambia este número para ajustar la duración de la animación
                // Generar números aleatorios para los dados
                int dado1 = (int) (Math.random() * 6) + 1;
                int dado2 = (int) (Math.random() * 6) + 1;
                
                // Generar Iconos
                Icon uno = new javax.swing.ImageIcon(getClass().getResource("/dados/1.png"));
                Icon dos = new javax.swing.ImageIcon(getClass().getResource("/dados/2.png"));
                Icon tres = new javax.swing.ImageIcon(getClass().getResource("/dados/3.png"));
                Icon cuatro = new javax.swing.ImageIcon(getClass().getResource("/dados/4.png"));
                Icon cinco = new javax.swing.ImageIcon(getClass().getResource("/dados/5.png"));
                Icon seis = new javax.swing.ImageIcon(getClass().getResource("/dados/6.png"));
                
                // Mostrar las imágenes de los dados aleatorios
                switch (dado1) {
                    case 1:
                        dadito1.setIcon(uno);
                        break;
                    case 2:
                        dadito1.setIcon(dos);
                        break;
                    case 3:
                        dadito1.setIcon(tres);
                        break;
                    case 4:
                        dadito1.setIcon(cuatro);
                        break;
                    case 5:
                        dadito1.setIcon(cinco);
                        break;
                    case 6:
                        dadito1.setIcon(seis);
                        break;
                }
                switch (dado2) {
                    case 1:
                        dadito2.setIcon(uno);
                        break;
                    case 2:
                        dadito2.setIcon(dos);
                        break;
                    case 3:
                        dadito2.setIcon(tres);
                        break;
                    case 4:
                        dadito2.setIcon(cuatro);
                        break;
                    case 5:
                        dadito2.setIcon(cinco);
                        break;
                    case 6:
                        dadito2.setIcon(seis);
                        break;
                }
            } else {
                // Detener la animación después de un número de actualizaciones definido
                timer.cancel();
                timer.purge();
                
                // Calcular el resultado final y mostrarlo
                int dado1 = (int) (Math.random() * 6) + 1;
                int dado2 = (int) (Math.random() * 6) + 1;
                int resultado = dado1 + dado2;
                Resultado.setText("Obtuviste: " + resultado);
            }
        }
    };
    
    // Ejecutar la tarea cada 100 ms (ajusta este valor según tus necesidades)
    timer.schedule(task, 0, 100);
}

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         iniciarAnimacionDados();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel dadito1;
    private javax.swing.JLabel dadito2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
