/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jorju
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTragaperras = new javax.swing.JButton();
        btnDados = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTragaperras.setBackground(new java.awt.Color(51, 0, 51));
        btnTragaperras.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        btnTragaperras.setForeground(new java.awt.Color(255, 255, 255));
        btnTragaperras.setText("TragaPerras");
        btnTragaperras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTragaperrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTragaperras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 190, 60));

        btnDados.setBackground(new java.awt.Color(51, 0, 51));
        btnDados.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        btnDados.setForeground(new java.awt.Color(255, 255, 255));
        btnDados.setText("Dados ");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 140, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casinoonline1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1050, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        // TODO add your handling code here:
        Dados D1 =new Dados();
        D1.setVisible(true);
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnTragaperrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTragaperrasActionPerformed
        // TODO add your handling code here:
        Tragaperras T1 = new Tragaperras();
        T1.setVisible(true);

    }//GEN-LAST:event_btnTragaperrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnTragaperras;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
