/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author Jorju
 */
public class Tragaperras extends javax.swing.JFrame {

    /**
     * Creates new form Tragaperras
     */
    int saldo ;
    int apuesta, gana; 
    
    public Tragaperras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapuesta = new javax.swing.JTextField();
        txtsaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tragamonedas/slot1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tragamonedas/slot2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tragamonedas/slot3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 0, 51));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 255));
        jLabel4.setText("TRAGAMONEDAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txtapuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapuestaActionPerformed(evt);
            }
        });
        getContentPane().add(txtapuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 121, -1));
        getContentPane().add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 121, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apuesta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, 20));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Saldo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, 60));

        resultado.setEditable(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 121, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resultado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-1175764893-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 450, 280));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tragamon.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animarSlots() {
    TimerTask task = new TimerTask() {
        int count = 0;
        int maxCount = 10; // Número máximo de iteraciones de la animación

        @Override
        public void run() {
            int n1 = (int) (Math.random() * 9) + 1;
            int n2 = (int) (Math.random() * 9) + 1;
            int n3 = (int) (Math.random() * 9) + 1;

            ImageIcon imagen1 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n1 + ".png");
            jLabel1.setIcon(imagen1);
            ImageIcon imagen2 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n2 + ".png");
            jLabel2.setIcon(imagen2);
            ImageIcon imagen3 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n3 + ".png");
            jLabel3.setIcon(imagen3);

            count++;
            if (count >= maxCount) {
                // La animación ha terminado, mostramos el resultado final
                mostrarResultado(n1, n2, n3);
                cancel(); // Detenemos el TimerTask
            }
        }

        private void mostrarResultado(int n1, int n2, int n3) {
        int apuesta = Integer.parseInt(txtapuesta.getText());
        int saldo = Integer.parseInt(txtsaldo.getText());
       int gana; 

   

    ImageIcon imagen1 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n1 + ".png");
    jLabel1.setIcon(imagen1);
    ImageIcon imagen2 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n2 + ".png");
    jLabel2.setIcon(imagen2);
    ImageIcon imagen3 = new ImageIcon("C:\\Users\\Jorju\\Documents\\NetBeansProjects\\JuegosAzar\\src\\tragamonedas\\slot" + n3 + ".png");
    jLabel3.setIcon(imagen3);

    if (n1 == n2 && n2 == n3 && n3 == n1) {
        resultado.setText("Premio Mayor!!!");
        gana = apuesta * 6;
        saldo += gana;
        txtsaldo.setText(String.valueOf(saldo));
    } else if (n1 == n2 || n2 == n3 || n3 == n1) {
        resultado.setText("Premio");
        gana = apuesta * 2;
        saldo += gana;
        txtsaldo.setText(String.valueOf(saldo));
    } else {
        resultado.setText("Juegue de Nuevo");
        saldo = saldo - apuesta;
        txtsaldo.setText(String.valueOf(saldo));
    }
}
    };

    Timer timer = new Timer();
    int delay = 100; // Retraso en milisegundos entre cada iteración de la animación
    timer.schedule(task, 0, delay);
}

    private void txtapuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapuestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           animarSlots();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tragaperras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField txtapuesta;
    private javax.swing.JTextField txtsaldo;
    // End of variables declaration//GEN-END:variables
}
